# Generated by Django 3.0.8 on 2021-02-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210214_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='work_experience',
            new_name='WorkExperience',
        ),
    ]
