# Generated by Django 3.0.8 on 2021-02-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210214_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('College', 'College'), ('Own', 'Own')], default='College', max_length=10),
        ),
    ]
