# Generated by Django 3.0.8 on 2021-02-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_project_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name_plural': 'Work Experience'},
        ),
    ]
