# Generated by Django 3.0.8 on 2021-02-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210215_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='link',
            field=models.CharField(default='', max_length=256),
        ),
    ]
