# Generated by Django 3.0.8 on 2021-02-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_workexperience_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=2056)),
                ('bio', models.CharField(max_length=256)),
                ('img', models.ImageField(null=True, upload_to='media/', verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Personal Info',
            },
        ),
    ]
