# Generated by Django 3.0.8 on 2021-03-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_personalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_blogs', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('total_claps', models.IntegerField(default=0)),
                ('total_fans', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'MediumStats',
            },
        ),
    ]
