# Generated by Django 3.0.8 on 2021-03-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_blogstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogstats',
            name='total_claps',
            field=models.CharField(max_length=2056),
        ),
        migrations.AlterField(
            model_name='blogstats',
            name='total_fans',
            field=models.CharField(max_length=2056),
        ),
        migrations.AlterField(
            model_name='blogstats',
            name='total_views',
            field=models.CharField(max_length=2056),
        ),
    ]
